services:
  api:
    container_name: house-valuations-api
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - ${API_PORT:-8000}:8000
    volumes:
      - ./backend:/code

  frontend:
    container_name: house-valuations-frontend
    build:
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
